# Generated by Django 5.2.4 on 2025-07-19 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='address33',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='title4',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
